import { verifyAccessToken } from '~/utils/jwt-utils';
import { unAuthorizedResponse } from '~/utils/response';

export default eventHandler(async (event) => {
  const userinfo = verifyAccessToken(event);
  if (!userinfo) {
    return unAuthorizedResponse(event);
  }

  await sleep(600);

  return useResponseSuccess([
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-27 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '60',
      leftResourceNum: '53',
      clinicLabel: '胡玉娟（内专）渝中',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '普通',
      doctorEmpNo: '482311',
      doctorName: '胡玉娟',
      doctorDuty: '主治医师',
      doctorDesc:
        '主治医师，重庆医科大学硕士研究生，从事小儿内分泌专科，擅长诊治性早熟、矮小症、甲状腺疾病、肥胖症、糖尿病、代谢性骨病等疾病。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDgyMzExX+iDoeeOieWonw==.png',
      totalCharges: '15',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'hu2yu4juan1（nei4zhuan1）yu2zhong1',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-26 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '75',
      leftResourceNum: '46',
      clinicLabel: '陈龙内分泌（内专）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '普通',
      doctorEmpNo: '480305',
      doctorName: '陈龙',
      doctorDuty: '主治医师',
      doctorDesc:
        '主治医师，1999-2004就读于重庆医科大学，获学士学位；2007-年在重庆医科大学附属儿童医院内分泌科工作至今，擅长小儿内分泌各种常见疾病，如儿童糖尿病、甲状腺疾病、性早熟等的诊治。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDgwMzA1X+mZiOm+mQ==.png',
      totalCharges: '15',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'chen2long2nei4fen1mi4（nei4zhuan1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-28 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '75',
      leftResourceNum: '40',
      clinicLabel: '陈龙内分泌（内专）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '普通',
      doctorEmpNo: '480305',
      doctorName: '陈龙',
      doctorDuty: '主治医师',
      doctorDesc:
        '主治医师，1999-2004就读于重庆医科大学，获学士学位；2007-年在重庆医科大学附属儿童医院内分泌科工作至今，擅长小儿内分泌各种常见疾病，如儿童糖尿病、甲状腺疾病、性早熟等的诊治。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDgwMzA1X+mZiOm+mQ==.png',
      totalCharges: '15',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'chen2long2nei4fen1mi4（nei4zhuan1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-06-19 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '50',
      leftResourceNum: '40',
      clinicLabel: '宋萃（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '特需',
      doctorEmpNo: '400756',
      doctorName: '宋萃',
      doctorDuty: '主任医师',
      doctorDesc:
        '博士，重庆医科大学附属儿童医院内分泌遗传代谢科 主任医师，副教授，硕士研究生导师，哈佛医学院访问学者。第三批重庆市儿科学学术技术后备人选。重庆医科大学第三批学术技术带头人后备人选。重庆医科大学附属儿童医院后备人才。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwNzU2X+Wui+iQgw==.png',
      totalCharges: '120',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'song4cui4（te4xu1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-06-17 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '45',
      leftResourceNum: '19',
      clinicLabel: '朱高慧（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午',
      registerLevel: '特需',
      doctorEmpNo: '400833',
      doctorName: '朱高慧',
      doctorDuty: '副主任医师',
      doctorDesc:
        '博士，副主任医师，美国芝加哥大学和辛辛那提儿童医院访问学者，擅长儿童矮小症、性早熟、甲状腺疾病、糖尿病等内分泌遗传代谢疾病诊治。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwODMzX+acsemrmOaFpw==.png',
      totalCharges: '90',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'zhu1gao1hui4（te4xu1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-28 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '60',
      leftResourceNum: '17',
      clinicLabel: '胡玉娟（内专）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '普通',
      doctorEmpNo: '482311',
      doctorName: '胡玉娟',
      doctorDuty: '主治医师',
      doctorDesc:
        '主治医师，重庆医科大学硕士研究生，从事小儿内分泌专科，擅长诊治性早熟、矮小症、甲状腺疾病、肥胖症、糖尿病、代谢性骨病等疾病。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDgyMzExX+iDoeeOieWonw==.png',
      totalCharges: '15',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'hu2yu4juan1（nei4zhuan1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-26 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '60',
      leftResourceNum: '16',
      clinicLabel: '胡玉娟（内专）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '普通',
      doctorEmpNo: '482311',
      doctorName: '胡玉娟',
      doctorDuty: '主治医师',
      doctorDesc:
        '主治医师，重庆医科大学硕士研究生，从事小儿内分泌专科，擅长诊治性早熟、矮小症、甲状腺疾病、肥胖症、糖尿病、代谢性骨病等疾病。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDgyMzExX+iDoeeOieWonw==.png',
      totalCharges: '15',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'hu2yu4juan1（nei4zhuan1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-27 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '60',
      leftResourceNum: '2',
      clinicLabel: '周莛（内专）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '普通',
      doctorEmpNo: '481593',
      doctorName: '周莛',
      doctorDuty: '主治医师',
      doctorDesc:
        '主治医师，硕士研究生，毕业于重庆医科大学，长期从事小儿内分泌及遗传代谢相关疾病，有丰富的临床诊治经验。擅长诊治性早熟、矮小症、甲状腺疾病、肥胖症、糖尿病等内分泌疾病及遗传代谢性疾病。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDgxNTkzX+WRqOiOmw==.png',
      totalCharges: '15',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'zhou1ting2（nei4zhuan1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-27 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '50',
      leftResourceNum: '1',
      clinicLabel: '朱岷（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '特需',
      doctorEmpNo: '400654',
      doctorName: '朱岷',
      doctorDuty: '主任医师',
      doctorDesc:
        '主任医师，教授，硕士研究生导师。重庆医科大学儿童医院内分泌遗传代谢科主任。中华医学会儿科学分会第十八届内分泌遗传代谢学组副组长，重庆市医学会儿科学分会内分泌遗传代谢学组组长。擅长诊治各种内分泌及遗传代谢性疾病。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwNjU0X+acseWytw==.png',
      totalCharges: '150',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'zhu1min2（te4xu1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-23 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '35',
      leftResourceNum: '0',
      clinicLabel: '陈立黎（内专）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '下午',
      registerLevel: '普通',
      doctorEmpNo: '480863',
      doctorName: '陈立黎',
      doctorDuty: '主治医师',
      doctorDesc:
        '主治医师，毕业于重庆医科大学，从事小儿内分泌科专科工作十余年，有丰富的临床经验。擅长诊治矮小症、性早熟、甲状腺疾病、肥胖症、糖尿病等内分泌疾病及遗传代谢性疾病。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDgwODYzX+mZiOeri+m7jg==.png',
      totalCharges: '15',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'chen2li4li2（nei4zhuan1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-26 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '20',
      leftResourceNum: '0',
      clinicLabel: '儿童超重肥胖门诊（朱高慧）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午',
      registerLevel: '特需',
      doctorEmpNo: '400833',
      doctorName: '朱高慧',
      doctorDuty: '副主任医师',
      doctorDesc:
        '博士，副主任医师，美国芝加哥大学和辛辛那提儿童医院访问学者，擅长儿童矮小症、性早熟、甲状腺疾病、糖尿病等内分泌遗传代谢疾病诊治。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwODMzX+acsemrmOaFpw==.png',
      totalCharges: '90',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin:
        'er2tong2chao1zhong4fei2pang4men2zhen3（zhu1gao1hui4）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-27 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '50',
      leftResourceNum: '0',
      clinicLabel: '宋萃（内专）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '普通',
      doctorEmpNo: '400756',
      doctorName: '宋萃',
      doctorDuty: '主任医师',
      doctorDesc:
        '博士，重庆医科大学附属儿童医院内分泌遗传代谢科 主任医师，副教授，硕士研究生导师，哈佛医学院访问学者。第三批重庆市儿科学学术技术后备人选。重庆医科大学第三批学术技术带头人后备人选。重庆医科大学附属儿童医院后备人才。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwNzU2X+Wui+iQgw==.png',
      totalCharges: '30',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'song4cui4（nei4zhuan1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-06-05 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '50',
      leftResourceNum: '0',
      clinicLabel: '宋萃（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '特需',
      doctorEmpNo: '400756',
      doctorName: '宋萃',
      doctorDuty: '主任医师',
      doctorDesc:
        '博士，重庆医科大学附属儿童医院内分泌遗传代谢科 主任医师，副教授，硕士研究生导师，哈佛医学院访问学者。第三批重庆市儿科学学术技术后备人选。重庆医科大学第三批学术技术带头人后备人选。重庆医科大学附属儿童医院后备人才。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwNzU2X+Wui+iQgw==.png',
      totalCharges: '120',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'song4cui4（te4xu1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-29 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '50',
      leftResourceNum: '0',
      clinicLabel: '宋萃（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '特需',
      doctorEmpNo: '400756',
      doctorName: '宋萃',
      doctorDuty: '主任医师',
      doctorDesc:
        '博士，重庆医科大学附属儿童医院内分泌遗传代谢科 主任医师，副教授，硕士研究生导师，哈佛医学院访问学者。第三批重庆市儿科学学术技术后备人选。重庆医科大学第三批学术技术带头人后备人选。重庆医科大学附属儿童医院后备人才。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwNzU2X+Wui+iQgw==.png',
      totalCharges: '120',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'song4cui4（te4xu1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-06-12 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '50',
      leftResourceNum: '0',
      clinicLabel: '宋萃（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '特需',
      doctorEmpNo: '400756',
      doctorName: '宋萃',
      doctorDuty: '主任医师',
      doctorDesc:
        '博士，重庆医科大学附属儿童医院内分泌遗传代谢科 主任医师，副教授，硕士研究生导师，哈佛医学院访问学者。第三批重庆市儿科学学术技术后备人选。重庆医科大学第三批学术技术带头人后备人选。重庆医科大学附属儿童医院后备人才。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwNzU2X+Wui+iQgw==.png',
      totalCharges: '120',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'song4cui4（te4xu1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-28 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '40',
      leftResourceNum: '0',
      clinicLabel: '熊丰（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午',
      registerLevel: '特需',
      doctorEmpNo: '400490',
      doctorName: '熊丰',
      doctorDuty: '主任医师',
      doctorDesc:
        '主任医师，教授，硕士研究生导师。国内外发表学术论文60余篇。主持、参研科研项目11余项。参编专著5余部。擅长诊断治疗多种小儿内分泌疾病和遗传代谢性疾病。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwNDkwX+eGiuS4sA==.png',
      totalCharges: '150',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'xiong2feng1（te4xu1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-24 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '60',
      leftResourceNum: '0',
      clinicLabel: '周莛（内分泌）渝中',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午,下午',
      registerLevel: '普通',
      doctorEmpNo: '481593',
      doctorName: '周莛',
      doctorDuty: '主治医师',
      doctorDesc:
        '主治医师，硕士研究生，毕业于重庆医科大学，长期从事小儿内分泌及遗传代谢相关疾病，有丰富的临床诊治经验。擅长诊治性早熟、矮小症、甲状腺疾病、肥胖症、糖尿病等内分泌疾病及遗传代谢性疾病。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDgxNTkzX+WRqOiOmw==.png',
      totalCharges: '15',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'zhou1ting2（nei4fen1mi4）yu2zhong1',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-27 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '15',
      leftResourceNum: '0',
      clinicLabel: '朱高慧（内专）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '下午',
      registerLevel: '普通',
      doctorEmpNo: '400833',
      doctorName: '朱高慧',
      doctorDuty: '副主任医师',
      doctorDesc:
        '博士，副主任医师，美国芝加哥大学和辛辛那提儿童医院访问学者，擅长儿童矮小症、性早熟、甲状腺疾病、糖尿病等内分泌遗传代谢疾病诊治。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwODMzX+acsemrmOaFpw==.png',
      totalCharges: '22',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'zhu1gao1hui4（nei4zhuan1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-06-03 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '45',
      leftResourceNum: '0',
      clinicLabel: '朱高慧（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午',
      registerLevel: '特需',
      doctorEmpNo: '400833',
      doctorName: '朱高慧',
      doctorDuty: '副主任医师',
      doctorDesc:
        '博士，副主任医师，美国芝加哥大学和辛辛那提儿童医院访问学者，擅长儿童矮小症、性早熟、甲状腺疾病、糖尿病等内分泌遗传代谢疾病诊治。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwODMzX+acsemrmOaFpw==.png',
      totalCharges: '90',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'zhu1gao1hui4（te4xu1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-27 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '45',
      leftResourceNum: '0',
      clinicLabel: '朱高慧（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午',
      registerLevel: '特需',
      doctorEmpNo: '400833',
      doctorName: '朱高慧',
      doctorDuty: '副主任医师',
      doctorDesc:
        '博士，副主任医师，美国芝加哥大学和辛辛那提儿童医院访问学者，擅长儿童矮小症、性早熟、甲状腺疾病、糖尿病等内分泌遗传代谢疾病诊治。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwODMzX+acsemrmOaFpw==.png',
      totalCharges: '90',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'zhu1gao1hui4（te4xu1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-06-10 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '45',
      leftResourceNum: '0',
      clinicLabel: '朱高慧（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午',
      registerLevel: '特需',
      doctorEmpNo: '400833',
      doctorName: '朱高慧',
      doctorDuty: '副主任医师',
      doctorDesc:
        '博士，副主任医师，美国芝加哥大学和辛辛那提儿童医院访问学者，擅长儿童矮小症、性早熟、甲状腺疾病、糖尿病等内分泌遗传代谢疾病诊治。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwODMzX+acsemrmOaFpw==.png',
      totalCharges: '90',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'zhu1gao1hui4（te4xu1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-29 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '30',
      leftResourceNum: '0',
      clinicLabel: '朱岷（内专）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午',
      registerLevel: '普通',
      doctorEmpNo: '400654',
      doctorName: '朱岷',
      doctorDuty: '主任医师',
      doctorDesc:
        '主任医师，教授，硕士研究生导师。重庆医科大学儿童医院内分泌遗传代谢科主任。中华医学会儿科学分会第十八届内分泌遗传代谢学组副组长，重庆市医学会儿科学分会内分泌遗传代谢学组组长。擅长诊治各种内分泌及遗传代谢性疾病。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwNjU0X+acseWytw==.png',
      totalCharges: '30',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'zhu1min2（nei4zhuan1）yu2',
    },
    {
      hisId: null,
      company_code: null,
      companyCode: 'wechat',
      hospitalCode: '994129',
      clinicDate: '2025-05-26 00:00:00',
      deptCode: '399694260',
      deptName: '内科系列',
      subDeptCode: '039',
      subDeptName: '内分泌科',
      totalResourceNum: '30',
      leftResourceNum: '0',
      clinicLabel: '朱岷（特需）渝',
      clinicFullLabel: '',
      room: '',
      timeDesc: '上午',
      registerLevel: '特需',
      doctorEmpNo: '400654',
      doctorName: '朱岷',
      doctorDuty: '主任医师',
      doctorDesc:
        '主任医师，教授，硕士研究生导师。重庆医科大学儿童医院内分泌遗传代谢科主任。中华医学会儿科学分会第十八届内分泌遗传代谢学组副组长，重庆市医学会儿科学分会内分泌遗传代谢学组组长。擅长诊治各种内分泌及遗传代谢性疾病。',
      doctorPhotoPath:
        'https://xinan1.zos.ctyun.cn/chcmu-static/doctor_img_250417/downloads/NDAwNjU0X+acseWytw==.png',
      totalCharges: '150',
      stopFlag: '0',
      clinicLocation: '',
      insuranceDeptCode: '',
      itemCode: '',
      itemName: '',
      itemClass: '',
      units: '',
      itemSpec: '',
      insuranceCode: '',
      doctorIdNo: '',
      departmentName: '',
      clinicLabelPinyin: 'zhu1min2（te4xu1）yu2',
    },
  ]);
});
