import { verifyAccessToken } from '~/utils/jwt-utils';
import { unAuthorizedResponse } from '~/utils/response';

export default eventHandler(async (event) => {
  const userinfo = verifyAccessToken(event);
  if (!userinfo) {
    return unAuthorizedResponse(event);
  }

  await sleep(600);

  return useResponseSuccess([
    {
      hisId: null,
      company_code: null,
      hospitalCode: '994223',
      deptCode: '399694260',
      deptName: '内科系列',
      deptDesc: null,
      level: '1',
      parentCode: null,
      parentName: null,
      children: [
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '011',
          deptName: '肠道门诊',
          deptDesc:
            '肠道门诊是诊治各种类型腹泻（特别是感染性腹泻）的专科门诊。腹泻是儿童常见胃肠道疾病，其表现为：解稀便、稀水便、黄稀粘液便、粘液血便、或脓血便等，可伴呕吐、发热、精神食欲差；重者可致脱水、电解质紊乱、代谢性酸中毒、心肌炎、脑炎、脓毒症、休克等。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'chang2dao4men2zhen3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '006',
          deptName: '风湿免疫科',
          deptDesc:
            '本专科成立于1979年，重庆市医学重点专科，集医疗、教学、科研为一体，为全国免疫缺陷病（PID）中心和西南风湿病诊治中心。主要诊治病种包括：关节炎与关节痛；反复感染和免疫缺陷病；过敏性紫癜、川崎病、系统性红斑狼疮、血管炎等风湿性疾病以及严重过敏反应、药物过敏等过敏性疾病。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'feng1shi1mian3yi4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '009',
          deptName: '感染科',
          deptDesc:
            '本专科主要诊治范围：1．儿童发热、肠炎、传染性单核细胞增多症等EB病毒感染、巨细胞病毒感染等；2．儿童黄疸、肝功能异常、婴儿肝炎综合征、乙肝、丙肝、脂肪肝、自身免疫性肝病、肝豆状核变性、糖原累积症、希特林缺陷、遗传代谢性肝病等肝病；3．儿童常见发热出疹性疾病（手足口病、水痘、幼儿急疹、猩红热等）、腮腺炎等；4．寄生虫病；5．儿童不明原因发热、肝大、脾大、胸腹水、结核病、侵袭性真菌感染等疑难疾病。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'gan3ran3ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '047',
          deptName: '感染消化科',
          deptDesc:
            '本专科主要诊治范围：1．儿童发热、EB病毒感染（包括传染性单核细胞增多症）、巨细胞病毒感染等；2．腹泻、腹痛、食欲差、排便困难、消化不良、腹胀、呕吐、血便；3．儿童黄疸、肝功能异常、婴儿肝炎综合征、乙肝、丙肝、脂肪肝、自身免疫性肝病、肝豆状核变性、糖原累积症、希特林缺陷、遗传代谢性肝病等肝病；4．儿童常见发热出疹性疾病（手足口病、水痘、幼儿急疹、猩红热等）、腮腺肿大等；5．寄生虫病、嗜酸性细胞增高；6．儿童不明原因发热、肝大、脾大、胸腹水、结核病、侵袭性真菌感染等疑难疾病。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'gan3ran3xiao1hua4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '026',
          deptName: '急救专业',
          deptDesc: '',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'ji2jiu4zhuan1ye4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '037',
          deptName: '康复科',
          deptDesc:
            '本专科系全国一流综合儿童康复中心，主要诊治各类发育障碍性疾病及继发性功能障碍。特色诊疗病种：高危儿、发育迟缓、孤独症谱系障碍、脑性瘫痪、脊髓损伤、各类颅脑及周围神经损伤后遗症、遗传代谢性疾病所致发育障碍、骨关节活动障碍、瘢痕等。特色治疗项目：肉毒毒素注射、经颅磁刺激、语言认知训练、高压氧、心理行为治疗、冲击波、针灸推拿、家庭训练指导。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'kang1fu4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '013',
          deptName: '临床研究',
          deptDesc: '',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'lin2chuang2yan2jiu1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '039',
          deptName: '内分泌科',
          deptDesc:
            '本专科是全国知名小儿内分泌遗传代谢诊治中心之一。 主要诊治多种小儿内分泌疾病和遗传代谢性疾病：各种矮小症、性早熟、甲状腺疾病、儿童糖尿病、性发育异常（小阴茎、小睾丸、外生殖器异常两性畸形等）、性发育延迟、性腺功能低下、肾上腺疾病、甲状旁腺疾病、下丘脑垂体疾病、骨发育代谢异常性疾病等。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'nei4fen1mi4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '001',
          deptName: '内科全科',
          deptDesc: '',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'nei4ke1quan2ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '020',
          deptName: '普通发热',
          deptDesc: '',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'pu3tong1fa1re4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '007',
          deptName: '肾脏内科',
          deptDesc:
            '本专科诊疗范围主要包括血尿蛋白尿待查、肾病综合征、肾炎、IgA肾病、遗传性肾脏疾病、各种继发性肾炎（过敏性紫癜、系统性红斑狼疮、ANCA相关性血管炎等）、肾小管酸中毒、Batter综合征、急性肾功能衰竭、慢性肾脏病（Ⅰ期、Ⅱ期、Ⅲ期、Ⅳ期及尿毒症期）、泌尿道感染（单纯或复杂型）、遗尿等肾脏疾病的诊治及管理。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'shen4zang4nei4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '056',
          deptName: '消化科',
          deptDesc:
            '本专科对儿童各种胃肠道疾病、肝病、营养相关性疾病及儿科消化内镜和内镜下诊疗具丰富的临床诊治经验，目前已开展儿童无痛胃镜、结肠镜、小肠镜、胶囊内镜检查以及肠内外营养各项支持技术、13C尿素呼气试验等。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'xiao1hua4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '040',
          deptName: '新生儿内科',
          deptDesc:
            '本专科是国家级临床重点专科、重庆市医学重点学科、重庆市市级危重新生儿救治中心。主要收治出生28天内新生儿及早产儿，对新生儿内科疾病、新生儿危重症、超低出生体重儿及儿内科常见疾病，如呼吸、感染、消化、神经系统等各种疾病具有丰富的临床诊断和治疗经验。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'xin1sheng1er2nei4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '043',
          deptName: '心血管内科',
          deptDesc:
            '本专科是西部地区小儿心血管疾病诊治中心、国家卫生部小儿先心病介入诊疗技术培训基地、重庆市先心病介入质控中心和儿童晕厥中心。诊疗疾病及范围：先天性心脏病包括房间隔缺损、室间隔缺损、动脉导管未闭、肺动脉瓣狭窄等；后天性心脏病包括心肌炎、心肌病、高血压、不明原因咯血、心律失常、心内膜弹力纤维增生症等；尤其是在肺动脉瓣狭窄、主动脉瓣狭窄球囊扩张成形术、肺动脉狭窄、主动脉缩窄球囊扩张术、冠状动脉瘘介入封堵、周围肺动静脉瘘介入封堵、侧枝血管介入封堵等高难度手术有重大突破。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'xin1xue4guan3nei4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '041',
          deptName: '呼吸科',
          deptDesc:
            '本专科是卫生部国家临床重点专科，重庆市医学专业重点学科，主要诊治各种肺炎、哮喘、喘息性疾病、慢性咳嗽、肺不张、胸腔积液、先天性肺及气道发育异常、气道狭窄、肺血管畸形、支气管扩张、弥漫性间质性肺疾病、肺脓肿等呼吸系统疾病，诊治水平全国领先。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'hu1xi1ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '028',
          deptName: '普内科',
          deptDesc: '',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'pu3nei4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '042',
          deptName: '神经内科',
          deptDesc:
            '本专科诊治范围：癫痫、颅内感染、神经肌肉病、神经遗传代谢病、神经免疫病、脑血管病、神经发育行为疾病。特色技术：生酮饮食、癫痫灶立体定位、神经危重症管理、神经电生理检查、经颅磁刺激、神经运动功能及神经心理评估。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'shen2jing1nei4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '045',
          deptName: '血液肿瘤内科',
          deptDesc:
            '本专科为西南地区领先的儿童血液肿瘤病中心，主要诊疗范围：儿童白血病和淋巴瘤；造血干细胞移植治疗技术；骨髓衰竭性疾病（再生障碍性贫血）；组织细胞疾病（噬血综合征和朗格罕细胞组织细胞增生症）；各种贫血性疾病； 各种溶血性疾病；各种出血性疾病（如血小板减少症，血友病等）；各种遗传性血液病；其他疑难杂症，如其各种不明原因的贫血、血小板减少、肝脾肿大、淋巴结包块或机体包块，不明原因发热，肺部混合感染等。',
          level: '2',
          parentCode: '399694260',
          parentName: '内科系列',
          children: null,
          pinyinOfDeptName: 'xue4ye4zhong3liu2nei4ke1',
        },
      ],
      pinyinOfDeptName: 'nei4ke1xi4lie4',
    },
    {
      hisId: null,
      company_code: null,
      hospitalCode: '994223',
      deptCode: '399694261',
      deptName: '外科系列',
      deptDesc: null,
      level: '1',
      parentCode: null,
      parentName: null,
      children: [
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '012',
          deptName: '肛肠外科',
          deptDesc:
            '主要诊治范围：肛肠外科、儿童腹部外科及新生儿外科疾病，各种腹腔镜微创手术。诊疗疾病包括：1.肛门直肠疾病（先天性巨结肠、肛门直肠畸形等），肛周感染；2.儿童排便异常（便秘、便血、大便失禁等）；3.儿童各种急腹症（阑尾炎、肠套叠、嵌顿疝、肠梗阻、消化道出血、消化道异物等）；4.各种腹部肿块、腹股沟疝、肠造瘘术后随诊；5.肠道疾病电子纤维结肠镜诊断及治疗。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'gang1chang2wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '049',
          deptName: '肝胆外科',
          deptDesc:
            '本专科主要诊治范围：肝脏疾病:各种良恶性肝脏肿瘤，肝脓肿，肝脏外伤，遗传代谢性肝病；胆道疾病:胆道闭锁，胆汁淤积性肝病，急慢性胆囊炎及胆道结石，胆管扩张症；胰腺疾病:急慢性胰腺炎，胰腺肿瘤，胰腺外伤；脾脏疾病:各种原因脾功能亢进，脾脏占位，脾外伤；各种终末期肝病肝移植治疗；各种出血性疾病介入治疗；肝胆胰脾疾病微创治疗。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'gan1dan3wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '029',
          deptName: '普外科',
          deptDesc:
            '本专科主要就诊范围:体表软组织肿块，先天性发育畸形，创伤，感染性疾病，急腹症，儿童各类急慢性伤口或创面的处理。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'pu3wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '008',
          deptName: '普外新生儿外科',
          deptDesc:
            '本专科以儿童普外微创外科中心为核心医疗技术，主要诊治范围包括：腹腔镜微创腹股沟疝、急性阑尾炎、急性肠套叠、美克尔憩室、先天性巨结肠、先天性直肠肛管畸形；先天性肠闭锁、幽门肥厚性狭窄、先天性肠旋转不良等多种新生儿疾病；先天性胆道闭锁、先天性胆总管囊肿等多种胆道疾病的微创治疗。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'pu3wai4xin1sheng1er2wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '010',
          deptName: '日间外科',
          deptDesc:
            '诊治范围：腹股沟疝（俗称疝气、气包等）。小儿外科最常见疾病之一，表现为腹股沟区甚至延伸至阴囊的肿块，常哭闹时包块突出，安静后可消失，很少自愈，嵌顿发生率高并可导致肠管坏死、睾丸缺血坏死等严重后果，故需早诊断早治疗。本病易与鞘膜积液、隐睾、睾丸肿瘤等混淆。门诊为宝宝行综合评估，可提供快速康复的微创腹腔镜手术、皮纹小切口日间手术等解决方案。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'ri4jian1wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '053',
          deptName: '神经外科',
          deptDesc:
            '本专科规模及诊治水平在国内儿童医院中位居前列。主要收治神经系统创伤、先天性疾病（如脑积水、蛛网膜囊肿、脑/脊膜膨出与脊髓栓系等）、颅内及椎管内肿瘤、难治性癫痫、颅内和椎管内血管性疾病及其他儿童神经系统疾病。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'shen2jing1wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '055',
          deptName: '烧伤整形科',
          deptDesc:
            '本专科是目前国内儿童医院名列前茅的整形中心及创伤中心。诊疗范围包含：颌面畸形（唇腭裂，颜面发育不良，耳畸形，鼻畸形等面部整形手术），手足畸形整复、需要手术整形治疗的皮肤病变及浅表包块，烧创伤及瘢痕，以及其他需要美容整形的手术。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'shao1shang1zheng3xing2ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '023',
          deptName: '胃肠外科',
          deptDesc:
            '诊治范围包括：急性腹痛，消化道梗阻、出血，腹部包块，消化道畸形等腹部疾病；皮肤、软组织感染，包块，腹股沟疝以及便秘、排便功能障碍等。\n本专科以微创外科手术为核心医疗技术，应用腹腔镜、肠镜、达芬奇机器人等进行各类手术。\n本专科常见疾病：腹股沟疝、急性阑尾炎、肠梗阻，肠套叠、美克尔憩室、肠重复畸形、先天性巨结肠、先天性肛门直肠畸形、腹腔包块，肝胆胰等器官急性炎症所致腹痛、黄疸及腹膜炎等；腹部外伤；肛肠外科疾病：肛周脓肿、肛瘘、痔疮等；以及其它普外科疾病。\n',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'wei4chang2wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '050',
          deptName: '胃肠新生儿外科',
          deptDesc:
            '本专科主要诊室范围：各种新生儿外科疾病，儿童腹部外科和肛肠外科疾病，微创手术治疗诊疗疾病：1.新生儿及儿童消化道畸形（胃十二指肠梗阻、肠闭锁、肠旋转不良、美克尔憩室、胃肠重复畸形、脐膨出等）、肛门直肠疾病（先天性巨结肠、同源病、先天性肛门闭锁、一穴肛、肛周脓肿、肛瘘等）；2.儿童各种急腹症（肠梗阻、阑尾炎、肠套叠、嵌顿疝、消化道出血、消化道异物等）；软组织感染；3.新生儿呕吐，新生儿腹胀，新生儿便血，新生儿急腹症（肠穿孔、肠造瘘、肠梗阻等），脐部畸形（脐窦、卵黄管囊肿、脐肠瘘、脐尿管瘘等）；4.先天性胆道畸形，各种体表及腹部肿块（腹腔囊肿，消化系统肿瘤等）；5.腹部微创外科手术；6.腹部外伤（肝胆胰脾胃肠）；7.排便功能异常（便秘、大便失禁），儿童排便管理，术后大便管理及生物反馈训练；8.小儿疝（腹股沟斜疝、脐疝、腹壁疝等）；9.肠道疾病电子纤维结肠镜诊断及治疗。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'wei4chang2xin1sheng1er2wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '051',
          deptName: '血管瘤专业',
          deptDesc:
            '本专业诊疗范围：婴幼儿血管瘤、血管畸形、淋巴管畸形的个体化综合治疗，脉管疾病介入微创手术治疗。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'xue4guan3liu2zhuan1ye4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '024',
          deptName: '新生儿外科',
          deptDesc:
            '主要诊治范围：1.新生儿及儿童消化道畸形（胃十二指肠梗阻、幽门狭窄、肠闭锁、肠旋转不良、美克尔憩室、胃肠重复畸形、脐膨出等），胎儿消化道畸形产前咨询；2.新生儿呕吐、腹胀，便秘、便血及新生儿急腹症（胃肠穿孔、肠造瘘、肠梗阻等），脐部畸形（脐炎、脐窦、卵黄管囊肿、脐肠瘘、脐尿管瘘等）；肛周及皮肤软组织感染（肛周脓肿、肛瘘等）；3.胃肠造瘘术后随访复查。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'xin1sheng1er2wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '044',
          deptName: '心胸外科',
          deptDesc:
            '本专科成立于1974年，历经四十余载，达到西部领先、国内先进水平，临床专科服务辐射至四川、云南、贵州、广西、湖北以及重庆所辖区县等地区。主要诊疗疾病包含：心脏方面（年均手术量1000例）:1．体外循环下各类先天性心脏病直视手术；2．超声引导下室间隔缺损、房间隔缺损及动脉导管未闭微创介入封堵术。普胸方面：各类先天性肺气道畸形（如先天性肺囊腺瘤、隔离肺等）、胸廓发育畸形（如鸡胸、漏斗胸等）、膈发育畸形（先天性膈疝、膈膨升等）、食管畸形（如食管闭锁、食管狭窄、食管裂孔疝及气管软骨食管异位症等）、纵隔肿瘤等。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'xin1xiong1wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '048',
          deptName: '肿瘤外科',
          deptDesc:
            '本专科主要诊疗范围：神经母细胞瘤、生殖瘤（骶尾部、腹膜后、卵巢畸胎瘤及卵黄囊瘤）、淋巴瘤、横纹肌肉瘤及软组织肉瘤、肝母细胞瘤、血管瘤及淋巴管瘤等各种复杂疑难实体肿瘤。能对肿瘤患儿实施整体的系列的个体化综合治疗，包括精细微创的开放手术（如：神经母细胞瘤的血管骨骼化切除手术）、微创手术（介入、腹腔镜）；非侵入手术（HIFU聚焦超声消融肿瘤）；基于基因检测、药物靶点检测的肿瘤个体化诊断及个体化化疗等复杂疑难罕见实体瘤的综合诊治。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'zhong3liu2wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '038',
          deptName: '麻醉镇静',
          deptDesc:
            '渝中院区:CT、核磁镇静请挂2诊室（星期天核磁请挂3诊室）其他检查项目镇静请挂1诊室。\n两江院区:CT、核磁镇静请挂一楼镇静中心，其他检查项目镇静请挂二楼镇静中心。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'ma2zui4zhen4jing4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '054',
          deptName: '骨科',
          deptDesc:
            '本专科主要诊疗范围：各种脊柱、四肢损伤及骨折，各种先天性及后天性骨及关节、手足畸形，骨关节及脊柱感染、肿瘤及类肿瘤、四肢软组织包块，肢体及脊柱疼痛，步态异常，运动损伤等。特长优势：脊柱（侧弯）畸形、发育性及病理性髋关节脱位、股骨头坏死、马蹄足、多并指（趾）等手足畸形、斜颈、创伤后遗症（骨不连，畸形愈合等）、慢性骨髓炎、脑瘫、肢体不等长、复杂儿童骨折，各种疑难儿童骨科疾病，成骨不全症等。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'gu2ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '052',
          deptName: '泌尿外科',
          deptDesc:
            '本专科主要诊疗范围：儿童常见及疑难泌尿生殖疾病。特长优势：尿道下裂等阴茎先天畸形、先天性肾积水等尿路畸形、泌尿生殖肿瘤综合治疗、腔镜微创技术、排尿功能障碍、尿动力及生物反馈治疗、其他疑难复杂疾病等。',
          level: '2',
          parentCode: '399694261',
          parentName: '外科系列',
          children: null,
          pinyinOfDeptName: 'mi4niao4wai4ke1',
        },
      ],
      pinyinOfDeptName: 'wai4ke1xi4lie4',
    },
    {
      hisId: null,
      company_code: null,
      hospitalCode: '994223',
      deptCode: '399694262',
      deptName: '专科系列',
      deptDesc: null,
      level: '1',
      parentCode: null,
      parentName: null,
      children: [
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '032',
          deptName: '耳鼻喉科',
          deptDesc:
            '本专科为西南最大的小儿耳鼻咽喉头颈疾病诊治、研究中心，学科专业在全国儿童专科医院排名第二，诊疗范围：急、慢性中耳炎，听力下降，鼻炎，鼻窦炎，鼻息肉，鼻出血，急、慢性扁桃体炎，鼾症，先天性喉气管、耳、鼻发育畸形，耳鼻喉外伤以及耳鼻咽喉肿瘤等疾病。',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'er3bi2hou2ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '035',
          deptName: '儿保科',
          deptDesc:
            '本专科对生长障碍、营养不良、食物过敏、佝偻病、注意缺陷多动障碍、语言障碍、孤独症谱系障碍、智力低下、学习困难、发育行为问题等诊治处于国内领先水平。开展孤独症谱系障碍综合训练、口腔功能干预、语言评估、构音训练、高危儿感知运动训练、家庭养育指导沙盘游戏治疗等治疗项目。',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'er2bao3ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '003',
          deptName: '激光中心',
          deptDesc:
            '温馨提示：本专科主要诊治范围：1. 各种红胎记: 鲜红斑痣、血管瘤、毛细血管扩张症、血管角皮瘤、血管球瘤、蜘蛛痣、早期增生性瘢痕。2. 各种黑胎记: 太田痣、咖啡斑、雀斑、黑子、外伤性纹身、艺术性纹身。3. 各种皮肤美容：皮肤紧致（嫩肤）、色素沉着、凹陷性瘢痕4. 其它疾病：痤疮、寻常疣、尖锐湿疣、皮赘、疣状痣、汗管瘤、化脓性肉芽肿。',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'ji1guang1zhong1xin1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '034',
          deptName: '精神心理科',
          deptDesc:
            '本专科对儿童注意缺陷多动障碍、孤独症谱系障碍、发育迟缓、学习困难、语言障碍、抽动症、咬指甲、擦腿综合征、睡眠障碍、情绪障碍、品行障碍等儿童精神心理行为问题及障碍的诊治；开展儿童精神心理治疗和家庭教育指导；开展各种精神心理测验及孤独症和发育迟缓患儿的干预训练。',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'jing1shen2xin1li3ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '033',
          deptName: '口腔科',
          deptDesc:
            '本专科主要诊治龋齿、牙列不齐、语音不清及口腔颌面颈部炎症、肿物、外伤、骨折、张口受限等疾病，以唇腭裂等畸形的序列治疗、儿童青少年牙颌畸形的功能性矫治及口腔舒适化治疗为特色。现开设口腔门诊、唇腭裂专家门诊、语音门诊、VIP门诊及口腔颌面外科病房。',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'kou3qiang1ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '019',
          deptName: '临床营养科',
          deptDesc:
            '本专科为“标准化临床营养科建设示范基地”，“肠内营养先进工作单位”、“儿童营养标准与规范培训基地”。主要针对儿童各种疾病状态下的医学营养管理，如内分泌遗传代谢病、营养不良、超重肥胖、慢性消化系统疾病、外科围手术期、原发性免疫缺陷、器官移植、难治性癫痫等疾病的营养治疗。',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'lin2chuang2ying2yang3ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '030',
          deptName: '皮肤科',
          deptDesc:
            '本专科主要诊治范围：1. 过敏性皮肤病：湿疹、特应性皮炎、荨麻疹、药疹等；2. 感染性皮肤病：带状疱疹、病毒疣、脓疱疮、真菌感染（癣）等；3. 少见或疑难皮肤病：先天或遗传性皮肤病等；4. 昆虫性及物理性皮肤病：虫咬性皮、痱、晒伤、鸡眼等；5. 皮肤红斑鳞屑：银屑病（牛皮癣）等；6. 皮肤血管炎：过敏性紫癜、皮肤变应性血管炎、结节性红斑等；7. 结缔组织病：红斑狼疮、皮肌炎、硬皮病等；8. 色素性皮肤病：白癜风、咖啡斑等；9. 毛发、粘膜及甲疾病：脱发、指甲病变、唇炎、外阴疾病等；10. 其他：痤疮、皮肤包块、梅毒等。',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'pi2fu1ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '031',
          deptName: '眼科',
          deptDesc:
            '本专科是集医疗、科研、教学为一体的儿童眼病诊疗中心；专注于儿童斜视、弱视、近视、先天性白内障、先天性上睑下垂、小儿泪道疾病、早产儿视网膜病变及小儿眼底病防治。特色技术涵盖：视功能训练、早产儿眼底筛查、角膜塑形术、高透氧性硬性角膜接触镜验配、超声乳化、微创玻切。',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'yan3ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '021',
          deptName: '药学',
          deptDesc: '',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'yao4xue2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '036',
          deptName: '中医科',
          deptDesc:
            '中医科成立于1958年，现已发展成集临床医疗、教学、科研为一体的中医儿科基地。主要应用中西医结合诊治反复呼吸道感染、哮喘、急慢性咳嗽；鼻炎、过敏性鼻炎、鼻窦炎、腺样体肥大；厌食、口臭、生长发育缓慢、便秘、腹泻、腹痛、口腔溃疡；多发性抽动症；特应性皮炎（湿疹）、青春痘；过敏性紫癜、血小板减少性紫癜；遗尿；汗证；睡眠障碍、夜啼；霰粒肿等疾病。',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'zhong1yi1ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '147',
          deptName: '疼痛中心',
          deptDesc:
            '疼痛中心诊疗范围：儿童慢性疼痛，包括头面部疼痛、四肢肌肉骨骼疼痛、脊柱源性疼痛、慢性原发性疼痛、神经病理性疼痛、慢性术后或创伤后疼痛、慢性关节疼痛、软组织疼痛、癌性疼痛、血管源性疼痛、自主神经紊乱性疼痛以及顽固性失眠、顽固性呃逆等。',
          level: '2',
          parentCode: '399694262',
          parentName: '专科系列',
          children: null,
          pinyinOfDeptName: 'teng2tong4zhong1xin1',
        },
      ],
      pinyinOfDeptName: 'zhuan1ke1xi4lie4',
    },
    {
      hisId: null,
      company_code: null,
      hospitalCode: '994223',
      deptCode: '399694263',
      deptName: '专病系列',
      deptDesc: null,
      level: '1',
      parentCode: null,
      parentName: null,
      children: [
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '058',
          deptName: '矮小症',
          deptDesc:
            '本专病诊治范围：各种原因导致的身材矮小症（包括生长激素缺乏症、家族性矮小、甲状腺功能减低、性早熟所致的矮小、小于胎龄儿、骨骼发育畸形以及多种慢性疾病所致的矮小等）。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'ai3xiao3zheng4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '059',
          deptName: '白癜风',
          deptDesc:
            '本专病诊治范围：白癜风。该病是一种后天性色素脱失性皮肤病，严重影响患者的容貌和心理健康。白癜风的治疗起效慢，需较长时间治疗，大部分患者通过系统和规范化的治疗，可以取得良好的效果。我科具备伍德氏灯、皮肤镜、308准分子激光仪、窄谱UVB、表皮移植机等多个检查和治疗设备。本专病门诊由经验丰富的医生坐诊，提供诊断、治疗、随访一条龙服务。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'bai2dian4feng1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '060',
          deptName: '瘢痕',
          deptDesc:
            '本专病诊治范围：遵照"早期干预、联合治疗、充分治疗"的瘢痕防治原则，根部患儿不同的瘢痕类型，患儿家长不同的需求，结合患儿的具体情况，制定个性化的瘢痕防治方案，包块压力治疗，减张治疗，支具矫形，外用药物，局部注射，光电治疗，手术治疗等，最大限度的改善瘢痕外观、恢复功能、安慰心理！',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'ban1hen2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '061',
          deptName: '便秘',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'bian4mi4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '062',
          deptName: '便血门诊',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'bian4xue4men2zhen3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '067',
          deptName: '痤疮',
          deptDesc:
            '本专病诊治范围：痤疮（青春痘）。为每一位患者进行全面评估，采用药物联合痤疮治疗仪、红蓝光、血管激光、光子技术、点阵激光等多种方法对痤疮的粉刺、脓疱、结节，以及痤疮后遗红斑及疤痕综合治疗，制定个性化治疗方案，迅速消退痤疮，减少复发，改善肤质。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'cuo2chuang1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '065',
          deptName: '抽动障碍',
          deptDesc:
            '本专病诊治范围：抽动障碍。该病在儿童和青少年时期起病，是以运动性抽动和(或) 发声性抽动为特征的神经精神疾病，发病率约为5~7%。经过正规合理的治疗后，多数患儿抽动症状可随年龄增长和大脑发育逐渐完善而减轻或缓解，大多数患儿成年后能像正常人一样工作生活。面对轻度抽动障碍，主要以健康教育、心理治疗为主，而对于中、重度的抽动障碍，主要以药物治疗为主，辅助心理行为治疗及经颅磁刺激治疗。本专病门诊由经验丰富的医生坐诊，为抽动障碍患儿及家长排忧解难。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'chou1dong4zhang4ai4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '066',
          deptName: '唇腭裂整形',
          deptDesc:
            '本专病诊治范围：唇腭裂。为每一位患儿进行全面评估，指导喂养，拟定个体化序列治疗方案，具体安排术前正畸、唇裂修补术时间、术后综合抗瘢痕程序、腭裂修补术时间、术后语音训练时间、唇鼻美容治疗时间、腭咽闭合评估时间、腭咽闭合不全手术时间、牙槽嵴裂修补时间、面中部发育不良矫正时间等，以期让患儿得到最理想的治疗。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'chun2e4lie4zheng3xing2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '064',
          deptName: '成骨不全',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'cheng2gu2bu4quan2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '063',
          deptName: '肠系膜淋巴结炎',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'chang2xi4mo2lin2ba1jie5yan2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '068',
          deptName: '胆道闭锁',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'dan3dao4bi4suo3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '070',
          deptName: '癫痫',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'dian1xian2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '069',
          deptName: '胆总管囊肿',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'dan3zong3guan3nang2zhong3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '072',
          deptName: '腹股沟疝',
          deptDesc:
            '本专病诊治范围：腹股沟疝（俗称疝气、气包等）。小儿外科最常见疾病之一，表现为腹股沟区甚至延伸至阴囊的肿块，常哭闹时包块突出，安静后可消失，很少自愈，嵌顿发生率高并可导致肠管坏死、睾丸缺血坏死等严重后果，故需早诊断早治疗。本病易与鞘膜积液、隐睾、睾丸肿瘤等混淆。门诊为宝宝行综合评估，可提供快速康复的微创腹腔镜手术、皮纹小切口日间手术等解决方案。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'fu4gu3gou1shan4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '073',
          deptName: '肝病',
          deptDesc:
            '我院为西部地区儿童肝病诊治中心，对疑难危重肝病诊治经验丰富。\n主要诊治疾病范围：\n（1）黄疸、肝功能异常、婴儿肝炎综合征、胆汁淤积、胆汁酸升高、乙肝、丙肝、EB病毒肝炎、巨细胞病毒肝炎、药物性肝损伤、毒物所致肝损伤、自身免疫性肝病、脂肪肝、遗传代谢性肝病（肝豆状核变性、糖原累积症、希特林蛋白缺陷症、NTCP缺陷症等）、肝硬化、肝功能衰竭等。\n（2）儿童肝病咨询随访，乙肝疫苗的咨询，乙肝母婴传播阻断随访。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'gan1bing4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '075',
          deptName: '孤独症',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'gu1du2zheng4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '076',
          deptName: '关节炎',
          deptDesc: '本专病诊治范围：关节肌肉疼痛性疾病，包括关节炎与关节痛。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'guan1jie2yan2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '074',
          deptName: '肛门直肠畸形',
          deptDesc:
            '主要诊治范围：先天性肛门直肠畸形（肛门狭窄、肛门闭锁、一穴肛等）、先天性巨结肠。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'gang1men2zhi2chang2ji1xing2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '079',
          deptName: '黄疸门诊',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'huang2dan3men2zhen3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '077',
          deptName: '鼾症',
          deptDesc:
            '儿童阻塞性睡眠呼吸暂停低通气综合征（OSAHS）是指由于睡眠过程中频繁出现部分或全部上气道阻塞导致扰乱儿童睡眠过程中的正常通气气流改变、睡眠结构改变从而引起的一系列病理生理变化。临床表现为夜间睡眠打鼾、张口呼吸、睡眠中反复惊醒、呼吸困难、遗尿、多汗、多动等，可能发生白天嗜睡但不多见。严重的病例可发生认知缺陷行为异常发育迟缓、心肺疾病等并发症。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'han1zheng4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '078',
          deptName: '黑痣整形',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'hei1zhi4zheng3xing2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '081',
          deptName: '结核感染及筛查',
          deptDesc:
            '门诊随访评估患者结核控制情况，以及药物不良反应，根据患者病情调整结核治疗方案。对结核初筛异常的儿童进行评估。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'jie2he2gan3ran3ji2shai1cha2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '080',
          deptName: '脊柱外科',
          deptDesc:
            '本专病诊治范围：脊柱脊髓的各种疾病，包括先天性脊柱侧弯（半椎体等）、特发性脊柱侧弯、颈椎畸形及先天畸形、脊柱后凸、峡部裂及脊柱滑脱、脊髓脊膜膨出，以及脊柱及附件的结核感染、结核，肿瘤性病变，嗜酸性性肉芽肿等。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'ji3zhu4wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '083',
          deptName: '淋巴管瘤',
          deptDesc:
            '儿童淋巴管瘤及淋巴管畸形、血管瘤血管畸形、脉管瘤的个体化综合治疗。特色技术：超声引导下淋巴管瘤、血管瘤、脉管瘤精准注射治疗（无辐射，需麻醉）、超声引导下淋巴管瘤、血管瘤热消融治疗、脉管瘤介入治疗。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'lin2ba1guan3liu2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '086',
          deptName: '泌尿系结石',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'mi4niao4xi4jie2shi2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '087',
          deptName: '泌尿系肿瘤',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'mi4niao4xi4zhong3liu2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '084',
          deptName: '慢性咳嗽',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'man4xing4ke2sou4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '085',
          deptName: '慢性肾脏病合并生长障碍多学科联合门诊',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName:
            'man4xing4shen4zang4bing4he2bing4sheng1zhang3zhang4ai4duo1xue2ke1lian2he2men2zhen3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '088',
          deptName: '免疫缺陷',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'mian3yi4que1xian4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '089',
          deptName: '尿道下裂',
          deptDesc:
            '临床表现为站立排尿常尿湿裤子，尿道开口异位、阴茎下弯、包皮分布异常。该病治疗难度较大，可伴发前列腺囊，不规范治疗可导致尿道下裂残废，严重影响患儿身心健康。本学科治疗尿道下裂经验丰富，针对不同类型选择最优方案，一次手术成功率高，居国内外前列，术后外观美观，严重并发症极少。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'niao4dao4xia4lie4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '090',
          deptName: '尿频',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'niao4pin2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '091',
          deptName: '排便功能异常',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'pai2bian4gong1neng2yi4chang2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '092',
          deptName: '排尿异常',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'pai2niao4yi4chang2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '093',
          deptName: '鞘膜积液',
          deptDesc:
            '诊治范围：鞘膜积液，女孩称纳克氏囊肿。该病在婴幼儿中较常见，发育过程中多数鞘膜积液可逐渐消失。临床表现为腹股沟区阴囊囊性包块，肿块较大可有坠胀感。一般≥2岁的鞘膜积液有手术指征。本病易与腹股沟斜疝、嵌疝、隐睾、睾丸肿瘤等混淆。门诊为宝宝行综合评估，提供美观、快速康复的治疗方案。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'qiao4mo2ji1ye4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '094',
          deptName: '情绪障碍',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'qing2xu4zhang4ai4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '071',
          deptName: '儿童遗尿症',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'er2tong2yi2niao4zheng4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '095',
          deptName: '神经肌肉病',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'shen2jing1ji1rou4bing4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '096',
          deptName: '肾积水',
          deptDesc:
            '肾积水是儿童常见的泌尿系畸形之一，发病率约为1/600-1/800，病因及治疗方案复杂。严重肾积水会影响肾脏功能，甚至导致慢性肾功能不全或肾功能衰竭。肾积水需明确病因，根据进展进行针对性治疗，规范治疗可取得较好的疗效。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'shen4ji1shui3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '097',
          deptName: '肾移植',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'shen4yi2zhi2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '100',
          deptName: '湿疹/特应性皮炎',
          deptDesc:
            '本专病诊治范围：特应性皮炎。该病是一种慢性复发性皮肤疾病，瘙痒剧烈，对孩子和家庭生活质量造成极大影响，需要长期规范的个体化精细管理。本专病门诊由经验丰富，具有国外留学经历的国内知名专家亲自坐诊，给您及孩子提供安全、有效的治疗方案，为您孩子的皮肤健康保驾护航。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'shi1zhen3/te4ying1xing4pi2yan2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '099',
          deptName: '生长发育',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'sheng1zhang3fa1yu4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '101',
          deptName: '胎记',
          deptDesc:
            '温馨提示：色素治疗目前仅在两江院区激光中心进行。  本专病诊治范围：胎记。该病可在出生时或出生后几个月出现，常分为红胎记和褐/黑胎记。大部分胎记为良性病变，少数可同时合并其它系统异常，严重者危及生命，因此需尽早筛查排除。本专病门诊可为宝宝提供全面的评估及制定合理的治疗方案，为宝宝的健康成长保驾护航。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'tai1ji4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '105',
          deptName: '听力障碍',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'ting1li4zhang4ai4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '102',
          deptName: '糖尿病',
          deptDesc:
            '本专病诊治范围：儿童糖尿病，为糖尿病患儿及家属提供自我监测、自我管理、心理调适等指导，帮助患儿及家属获取糖尿病相关知识,同时进行糖尿病并发症的筛查，为糖尿病患儿提供专业且个性化的治疗方案。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'tang2niao4bing4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '103',
          deptName: '特殊儿童疫苗接种',
          deptDesc:
            '特殊健康状态儿童疫苗评估与接种门诊，主要包括：早产、先天性心脏病、癫痫及其他神经系统慢性疾病、遗传代谢性疾病、血液系统肿瘤（白血病、淋巴瘤、嗜血综合征）、肿瘤（除血液系统肿瘤外）、原发性免疫缺陷病、慢性肝病及黄疸、支气管哮喘、器官移植、造血干细胞移植、长期口服激素药物（强的松、甲强龙、他克莫司、甲氨蝶呤、雷公藤等）、长期使用生物制剂。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'te4shu1er2tong2yi4miao2jie1zhong3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '104',
          deptName: '疼痛门诊',
          deptDesc:
            '诊疗范围：慢性疼痛（持续超过3个月），如头痛，关节痛、软组织疼痛、功能性腹痛、癌性疼痛、神经病理性疼痛、慢性术后或创伤后疼痛、血管源性疼痛、自主神经紊乱性疼痛等，治疗方法包括各种药物治疗、物理治疗、认知行为治疗、影像引导下治疗等。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'teng2tong4men2zhen3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '111',
          deptName: '哮喘',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xiao4chuan3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '110',
          deptName: '小儿妇科(中医)',
          deptDesc:
            '小儿妇科专科门诊成立于2002年，主要应用中西医结合诊治小儿外阴炎、阴道炎、月经失调（主要是痛经、青春期功血）、性早熟等疾病。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xiao3er2fu4ke1(zhong1yi1)',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '117',
          deptName: '血管瘤/脉管畸形',
          deptDesc:
            '"本专病诊疗范围：婴幼儿血管瘤、血管畸形、淋巴管畸形的个体化综合治疗，脉管疾病微创介入治疗\n诊疗疾病:\n1.\t血管瘤：婴幼儿血管瘤、先天性血管瘤、肉芽肿性血管瘤、角化血管瘤、卡波西血管内皮瘤、KM综合征等；\n2.\t血管畸形：静脉畸形，动静脉畸形，动静脉瘘，KT综合征，PW综合征，以及各种复杂脉管畸形；\n3.\t淋巴管畸形：大囊型、微囊型淋巴管瘤，腹腔淋巴管瘤（肠系膜囊肿、网膜囊肿等），淋巴水肿，淋巴漏等；\n4.\t综合介入治疗：各种复杂或深部血管瘤（肝脏血管瘤、脾脏血管瘤等），血管畸形，淋巴管畸形，腹部肿瘤等"',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xue4guan3liu2/mai4guan3ji1xing2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '118',
          deptName: '血管瘤激光诊疗',
          deptDesc:
            '本专病诊治范围：血管瘤。该病为儿童最常见的先天性良性肿瘤，常位于体表皮肤，在快速生长期可继发溃疡、压迫重要器官，消退期可残留毛细血管扩张和多余皮肤等，影响患儿容貌及造成功能影响。本专病门诊可为宝宝提供综合评估及治疗方案，让患儿尽早恢复正常皮肤，以利于自信健康地成长。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xue4guan3liu2ji1guang1zhen3liao2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '119',
          deptName: '血管炎肾损伤',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xue4guan3yan2shen4sun3shang1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '109',
          deptName: '鲜红斑痣',
          deptDesc:
            '本专病诊治范围：鲜红斑痣（又名葡萄酒色痣，俗称红胎记）。该病多数终生不退，并随年龄增长进行性加重，少数患儿还可合并颅内血管畸形、青光眼等其他系统病变，严重影响患儿的容貌及身心健康。因此，常需早诊断早治疗。本专病门诊由全国知名专家坐诊，并配备有脉冲染料激光及光动力等先进治疗设备，可为宝宝提供全面的评估及制定合理的综合治疗方案。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xian1hong2ban1zhi4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '115',
          deptName: '胸廓畸形',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xiong1kuo4ji1xing2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '113',
          deptName: '心律失常',
          deptDesc:
            '本专病诊治范围：各种类型的心律失常。包括窦性心动过缓、窦性停搏、窦房传导阻滞、房室传导阻滞；各种类型早搏（房性早搏、室性早搏、交界性早搏）、窦性心动过速、心房颤动、心房扑动、房性心动过速、室性心动过速、阵发性室上性心动过速（房室结折返性心动过速、房室折返性心动过速）等，临床表现为心慌、胸闷、头昏、乏力、黑矇等，严重者发生晕厥、抽搐甚至导致临床猝死。其治疗包括药物治疗、射频消融治疗和器械植入治疗。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xin1lu:4shi1chang2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '106',
          deptName: '先天性心脏病（内科介入）',
          deptDesc:
            '先心介入专病诊治范围（由心血管内科医师出诊）：室间隔缺损、房间隔缺损、动脉导管未闭、冠状动脉瘘、肺动静脉瘘、肺隔离症、侧枝血管封堵、肺-支气管血管畸形、肺动脉瓣狭窄、主动脉瓣狭窄、主动脉缩窄、分支肺动脉狭窄、有治疗指征的卵圆孔未闭以及复杂先心病的心导管术及造影检查等。临床表现：自幼反复呼吸道感染、生长发育落后、不明原因咯血、哭吵后、运动后唇面青紫或紫绀，不明原因胸痛、手指、脚指甲床紫绀或青紫、不明原因活动后心累等。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xian1tian1xing4xin1zang4bing4（nei4ke1jie4ru4）',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '107',
          deptName: '先天性心脏病（外科手术）',
          deptDesc:
            '本专病诊治范围（由胸心外科医师出诊）：室间隔缺损、房间隔缺损、动脉导管未闭、肺动脉狭窄、大动脉转位、肺动脉闭锁、右心室双出口、完全型房室间隔缺损、主动脉弓中断、主动脉缩窄、肺静脉异位引流、法洛氏四联症、单心室、儿童心脏瓣膜畸形、先天性心脏病合并气管狭窄等各种类型的先心病以及儿童心脏肿瘤、感染性心内膜炎等。开展单纯超声引导下微创经皮房间隔缺损、动脉导管未闭介入封堵，小切口经胸室间隔缺损微创封堵，既避免了患儿的放射线暴露，也避免传统外科手术的长切口，深受患儿及家长欢迎。同时也常规开展下腋下小切口先心病手术，胸腔镜微创治疗先天性血管环、动脉导管未闭等微创先心病手术。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xian1tian1xing4xin1zang4bing4（wai4ke1shou3shu4）',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '116',
          deptName: '学习困难',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xue2xi2kun4nan2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '108',
          deptName: '先心术后随访',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xian1xin1shu4hou4sui2fang3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '121',
          deptName: '血友病',
          deptDesc:
            '血友病是一组由于凝血因子Ⅷ或凝血因子Ⅸ的基因缺陷引起的X染色体连锁的隐性遗传性出血性疾病，主要分为血友病A（FⅧ缺乏）和血友病B（FⅨ缺乏）两类。这类疾病在患者出生时即可发病，并可能伴随患者一生。主要表现包括：皮肤粘膜出血、关节积血、肌肉出血和血肿、创伤或手术后出血不止或难止等，以及出血相关表现，如出血部位的疼痛、活动障碍等。儿童血友病专病门诊是一个专门针对上述患者设立的专业门诊，诊疗范围主要涵盖了血友病及其他先天性出血性疾病的专业诊断、评估、治疗方案制定、实施以及随访管理等。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xue4you3bing4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '142',
          deptName: '心脏康复',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xin1zang4kang1fu4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '126',
          deptName: '异常步态及姿势康复',
          deptDesc:
            '诊治范围：异常步态、异常姿势。儿童异常体态可导致多方面危害，常见驼背、脊柱侧弯、斜颈、骨盆倾斜、高低肩、扁平足、高弓足、八字步（X型腿、O型腿）、鸭步、醉酒步态、蹒跚步态等。不积极干预会影响生长发育、诱发疼痛、压迫神经并影响心理健康。专病门诊对孩子进行专业评估，寻找病因，让孩子少走弯路，及时得到个性化、精准治疗。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yi4chang2bu4tai4ji2zi1shi4kang1fu4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '123',
          deptName: '遗传性肾病',
          deptDesc:
            '该专病门诊主要针对单基因突变所致肾病，这部分患儿临床治疗效果差，往往对激素及免疫抑制剂多药耐药，根据指南建议，遗传性肾病患儿需终身随访，其中包括该类患儿的预防接种、白蛋白及免疫支持、遗传咨询、选择肾移植时机等，我院肾脏科特开设遗传性肾病专病门诊，能更为系统地随访及管理病人。近年来，肾脏科着力研究肾病综合征遗传学机制，诊治水平处于国内领先，积累了丰富的临床及科研经验。本专病门诊由肾脏科专家坐诊，为遗传性肾病患儿及家属排忧解难。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yi2chuan2xing4shen4bing4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '018',
          deptName: '遗传咨询',
          deptDesc:
            '本专病诊治范围：新生儿筛查结果异常者；高度警惕遗传代谢性疾病者；需行新生儿疾病筛查者； 明确诊断的甲低、苯丙酮尿症及串联质谱筛查的各种氨基酸代谢障碍、有机酸尿症和脂肪酸氧化障碍等遗传代谢性疾病；相关检查结果的解读如串联质谱、尿有机酸及基因报告等。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yi2chuan2zi1xun2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '128',
          deptName: '隐睾',
          deptDesc:
            '隐睾是儿童最常见生殖器先天畸形，临床表现为阴囊空虚，睾丸位置异常，容易被误诊。不规范治疗常导致睾丸萎缩，是男性不育或睾丸癌变的重要原因。目前推荐6月~1岁行手术治疗。本学科诊治隐睾经验丰富，可选择皮纹小切口或微创腹腔镜手术。术后伤口美观，睾丸位置满意，有助于睾丸发育及分泌激素，疗效位居国内外前列。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yin3gao1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '125',
          deptName: '乙肝临床治愈门诊',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yi3gan1lin2chuang2zhi4yu4men2zhen3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '130',
          deptName: '幽门螺杆菌感染',
          deptDesc:
            '本专病诊治范围：有上腹痛、恶心、呕吐、纳差、饱胀等消化不良症状疑诊儿童幽门螺杆菌感染者；消化性溃疡伴幽门螺杆菌感染；儿童家庭有幽门螺杆菌感染或胃癌患者需咨询者；不明原因缺铁性贫血；难治性ITP；幽门螺杆菌感染计划长期服用NSAIDs(包括低剂量阿司匹林)；其他各种原因疑幽门螺杆菌感染者；明确幽门螺杆菌感染需治疗者。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'you1men2luo2gan3jun1gan3ran3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '122',
          deptName: '夜啼症',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'ye4ti2zheng4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '127',
          deptName: '银屑病',
          deptDesc:
            '"银屑病，又称牛皮癣，约1/3始于儿童。该病不仅给患儿带来沉重的身心负担，持续的炎症反应还可能导致如关节炎、心血管疾病和代谢综合征等一系列并发症。由于儿童的生理特点，治疗必须兼顾疗效和长期安全性。\n银屑病专病门诊由经验丰富的教授级专家坐诊，为你提供科学、有效的治疗方案。\n"',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yin2xie4bing4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '129',
          deptName: '营养与喂养',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'ying2yang3yu3wei4yang3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '131',
          deptName: '语言障碍康复治疗',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yu3yan2zhang4ai4kang1fu4zhi4liao2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '138',
          deptName: '支气管炎/肺炎',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zhi1qi4guan3yan2/fei4yan2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '098',
          deptName: '肾脏膀胱肿瘤',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'shen4zang4pang2guang1zhong3liu2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '134',
          deptName: '针灸/推拿康复门诊',
          deptDesc:
            '以中医理论为基础，开展中医各类康复治疗技术，包括针灸、推拿、穴位注射、小针刀、穴位贴敷、中药封包、中药熏蒸、口服中药汤剂等。本专病诊治范围：偏瘫、截瘫、孤独症、智力低下、发育迟缓、脑出血、脑梗塞、抽动、多动、癫痫等疾病的中医康复治疗；以及胃肠功能、呼吸功能的中医康复调理。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zhen1jiu3/tui1na2kang1fu4men2zhen3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '140',
          deptName: '智力低下',
          deptDesc:
            '本专病诊治范围：儿童智能语言发育障碍，智力低下，智能语言倒退的病因诊断，康复治疗，长期管理。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zhi4li4di1xia4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '141',
          deptName: '肿瘤消融微创治疗',
          deptDesc:
            '特色技术：血管瘤超声引导下消融治疗、淋巴管瘤超声引导下注射治疗、肝脏肿瘤微波消融治疗。甲状腺结节的诊断与治疗，乳腺肿瘤、甲状腺结节等无切口微创微波消融治疗，微创腔镜技术。硬纤维瘤消融治疗、各类软组织肿瘤诊断与治疗。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zhong3liu2xiao1rong2wei1chuang4zhi4liao2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '139',
          deptName: '治未病',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zhi4wei4bing4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '136',
          deptName: '支气管肺发育不良',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zhi1qi4guan3fei4fa1yu4bu4liang2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '137',
          deptName: '支气管扩张',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zhi1qi4guan3kuo4zhang1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '132',
          deptName: '再生障碍性贫血',
          deptDesc:
            '"再障专病诊治范围：包括各种原因所致血细胞减少、不明原因发热、贫血、出血等怀疑再生障碍性贫血患者\n专病门诊时间：每月第一周的周四上午，渝中院区门诊2楼\n"',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zai4sheng1zhang4ai4xing4pin2xue4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '143',
          deptName: '周围血管疾病',
          deptDesc:
            '肝胆外科从事血管外科疾病诊疗多年，有着丰富的经验。本专科主要处理多种血管外科疾病：\n1）肺血栓、静脉血栓、静脉炎、血栓后综合征；\n2）动脉瘤、动脉血栓、动静脉瘘、动脉狭窄；\n3）创伤性出血、医源性出血等。\n针对不同病情，采取适当的药物治疗或介入/手术治疗。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zhou1wei2xue4guan3ji2bing4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '133',
          deptName: '造血干细胞移植',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zao4xue4gan1xi4bao1yi2zhi2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '135',
          deptName: '整形手足外科',
          deptDesc:
            '本专病诊治范围：先天、后天手足四肢畸形、包块（肿瘤）及甲病。辅以显微外科技术，使治疗最优化、微创化。可同时分离多个手指的并指，切除多指（趾）的同时矫正手指、足趾的侧偏、甲畸形并丰满指（趾）体。可重建拇指发育不良、缺如及手功能障碍，复杂手足畸形的治疗达国际水平。采用保甲技术治疗甲沟炎、甲母痣等急、慢性甲病。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zheng3xing2shou3zu2wai4ke1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '153',
          deptName: '乙肝功能性治愈',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yi3gan1gong1neng2xing4zhi4yu4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '112',
          deptName: '斜弱视',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xie2ruo4shi4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '150',
          deptName: '食物过敏',
          deptDesc:
            '食物过敏是儿童常见的过敏性疾病之一，见于5%-10%的儿童，发病率有升高趋势，影响儿童生长发育。早期食物过敏可能增加后期患其他过敏性疾病的风险。食物过敏专病门诊由具有多年食物过敏诊疗和科研经历的专家出诊，遵循食物过敏询证医学证据、结合儿保专业特色，做出正确的诊断和随访管理，给予营养指导，保障儿童良好生长。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'shi2wu4guo4min3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '162',
          deptName: '神经母细胞瘤',
          deptDesc:
            '本专病门诊诊治范围：儿童神经母细胞瘤，为患儿提供全程、全周期、多学科联动的综合治疗，血管骨骼化手术，个体化化疗，免疫治疗，靶向治疗，放疗，干细胞移植等，做到早期诊断与精准分型，制定个体化治疗方案和综合管理。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'shen2jing1mu3xi4bao1liu2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '157',
          deptName: '高危儿',
          deptDesc:
            '本专科是国家级临床重点专科、国家级新生儿保健特色专科、国家级儿童早期发展示范基地、重庆市医学重点学科、重庆市市级危重新生儿救治中心。高危儿专病门诊主要对高危儿的呼吸、消化、神经、心脏方面等问题进行早期识别及指导，监测体格生长及营养管理、神经行为发育监测、监测疾病转归、开展特殊检查及个体化早期干预等具有丰富的临床诊断和治疗经验。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'gao1wei1er2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '120',
          deptName: '血管炎',
          deptDesc:
            '"血管炎专病门诊主要针对儿童ANCA相关性血管炎、过敏性紫癜、系统性红斑狼疮，该类疾病常累及全身多个脏器，肾脏是最常受累器官，严重者可进展至终末期肾病，为规范儿童血管炎诊疗过程，实现合理的个体化治疗，肾脏科特开设儿童血管炎专病门诊。\n我科王墨主任牵头，承担""十四五""科技部重点研发计划项目《儿童AAV肾损伤风险评估体系建设及精准诊疗策略研究》，牵头撰写《中国儿童抗中性粒细胞胞质抗体相关性肾炎诊断与治疗临床实践指南（2023）》，有丰富的诊治经验，本专病门诊由肾脏科专家坐诊，有助于血管炎患儿全周期管理，提高管理延续性，改善患儿预后。\n"',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xue4guan3yan2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '159',
          deptName: '脊髓损伤康复治疗',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'ji3sui3sun3shang1kang1fu4zhi4liao2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '151',
          deptName: '语言迟缓',
          deptDesc:
            '儿童早期的语言发育迟缓可能会对未来的学业表现、心理行为产生深远影响。儿保科语言迟缓专病门诊拥有专业医疗团队，牵头国家级语言康复重点课题、参编行业专著，常年负责全国专科规范化培训及家庭干预指导，依托多学科专业背景的优势，建成以动态语言发育评估为基础、以自然语境下的语言康复为目标的儿童语言发育诊疗模式。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yu3yan2chi2huan3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '149',
          deptName: '注意缺陷多动障碍',
          deptDesc:
            '注意缺陷多动障碍，俗称“多动症”，是儿童常见慢性发育障碍性疾病，主要表现为注意缺陷、多动和冲动，50%以上患儿症状持续至成人，65%患儿存在一种或多种共患病，严重损害儿童的学业及生活。该门诊由高年资儿保医生组成专业诊疗团队，为儿童提供专业的诊断和评估，应用执行功能训练等综合干预服务，让儿童发挥最佳潜能。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zhu4yi4que1xian4duo1dong4zhang4ai4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '156',
          deptName: '运动损伤',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yun4dong4sun3shang1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '160',
          deptName: '意识障碍康复治疗',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'yi4shi1zhang4ai4kang1fu4zhi4liao2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '148',
          deptName: '先天性肺畸形',
          deptDesc:
            '先天性肺畸形（congenital lung malformations，CLM）是罕见的肺部发育异常，是一系列疾病的统称，其包括先天性肺气道畸形（CPAM）、支气管肺隔离症（BPS）、支气管囊肿（BC）及先天性肺叶气肿（CLE）。最常见的是先天性肺气道畸形（CPAM）与肺隔离症（PS）。这些先天性肺部病变大部分可以在妊娠期间产检发现，出生后患儿的主要影响是病灶内感染，以及远期发生恶变的可能。\n该专病门诊提供产前遗传咨询及出生后诊治方案建议。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'xian1tian1xing4fei4ji1xing2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '154',
          deptName: '手足畸形（骨科）',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'shou3zu2ji1xing2（gu2ke1）',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '152',
          deptName: '脂肪肝',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'zhi1fang2gan1',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '158',
          deptName: 'PID移植血液/免疫联合门诊',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'PIDyi2zhi2xue4ye4/mian3yi4lian2he2men2zhen3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '155',
          deptName: '骨肿瘤',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'gu2zhong3liu2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '082',
          deptName: '髋关节发育不良',
          deptDesc:
            '本专病由我科经验丰富的从医数十年的医生出诊，诊治范围：新生儿髋关节筛查，髋关节发育不良的诊治，股骨头缺血性坏死的早期保守治疗以及后期常见并发症的预防、处理，各种原因引起的髋关节疼痛，骨盆倾斜，外伤骨折脱位，髋关节肿瘤及各种病变。',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'kuan1guan1jie2fa1yu4bu4liang2',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '161',
          deptName: '神经发育迟缓康复',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'shen2jing1fa1yu4chi2huan3kang1fu4',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '163',
          deptName: '吞咽障碍康复治疗',
          deptDesc: '',
          level: '2',
          parentCode: '399694263',
          parentName: '专病系列',
          children: null,
          pinyinOfDeptName: 'tun1yan4zhang4ai4kang1fu4zhi4liao2',
        },
      ],
      pinyinOfDeptName: 'zhuan1bing4xi4lie4',
    },
    {
      hisId: null,
      company_code: null,
      hospitalCode: '994223',
      deptCode: '399694264',
      deptName: '护理系列',
      deptDesc: null,
      level: '1',
      parentCode: null,
      parentName: null,
      children: [
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '014',
          deptName: 'PICC导管护理',
          deptDesc: '',
          level: '2',
          parentCode: '399694264',
          parentName: '护理系列',
          children: null,
          pinyinOfDeptName: 'PICCdao3guan3hu4li3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '015',
          deptName: '伤口护理',
          deptDesc: '',
          level: '2',
          parentCode: '399694264',
          parentName: '护理系列',
          children: null,
          pinyinOfDeptName: 'shang1kou3hu4li3',
        },
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '016',
          deptName: '造口护理',
          deptDesc: '',
          level: '2',
          parentCode: '399694264',
          parentName: '护理系列',
          children: null,
          pinyinOfDeptName: 'zao4kou3hu4li3',
        },
      ],
      pinyinOfDeptName: 'hu4li3xi4lie4',
    },
    {
      hisId: null,
      company_code: null,
      hospitalCode: '994223',
      deptCode: '405618096561233921',
      deptName: '教学门诊系列',
      deptDesc: null,
      level: '1',
      parentCode: null,
      parentName: null,
      children: [
        {
          hisId: null,
          company_code: null,
          hospitalCode: '994223',
          deptCode: '146',
          deptName: '教学门诊（儿童保健科）',
          deptDesc: '',
          level: '2',
          parentCode: '405618096561233921',
          parentName: '教学门诊系列',
          children: null,
          pinyinOfDeptName: 'jiao4xue2men2zhen3（er2tong2bao3jian4ke1）',
        },
      ],
      pinyinOfDeptName: 'jiao4xue2men2zhen3xi4lie4',
    },
  ]);
});
